### ISSUE TITLE
Weekly Scrum - [March 5th, 2021]

### ISSUE THREAD

**Issue by Simon-Yacoub** [SYSC4806-Project/4806-Project#20]
This week we decided on a system design and came up with some early concepts for our project. 
Next week I will be working on the database schema diagram and shipping out the feature to displaying all available shops to customers.
Nothing is holding me back ;D

**Comment by brougy** [comment]
- This week, I did some research on design and architecture then discussed with the team and decided on the main designs and concepts of the system. 

- I will be working on creating a feature that allows the merchant to view/create/edit/remove a shop. 

- Nothing is holding me back as of yet, but you never know what kinda bugs will sneak on you.

**Comment by danish1371** [comment]
- This week we did the system design 
- Next week I will be working on completing/fixing the log in and register features
- Nothing is holding me back right now

**Comment by sandeeplayam** [comment]
- This week just like every other team member, I came up with a system deisgn/architecture. During this scrum we came 
   together to discuss our designs and came up with our final design of the system together.

- For next week ill be working on initializing the project, authentication feature and continuous integration setup with 
  TravisCI/Heroku

- As of right now its mostly going fine, just the initial struggles of getting a project started because its hard to visualize the 
   entire project. After taking the time to come up with a system design it has helped tremendously in moving forward with 
   the process of developing the project.
